[theme]
primaryColor = "#0284c7"
backgroundColor = "#dbeafe"
secondaryBackgroundColor = "#f0f9ff"
textColor = "#0c4a6e"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
headless = true
port = 8501
